"""empty message

Revision ID: 704d0539dc9b
Revises: c1bbd1bee8c2
Create Date: 2018-07-18 23:14:16.174248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704d0539dc9b'
down_revision = 'c1bbd1bee8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('top8url', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'top8url')
    # ### end Alembic commands ###
