"""empty message

Revision ID: 7090ff35b252
Revises: a9bbb821a983
Create Date: 2018-07-19 12:48:05.915524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7090ff35b252'
down_revision = 'a9bbb821a983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck_cards', sa.Column('sideboard', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deck_cards', 'sideboard')
    # ### end Alembic commands ###
