"""empty message

Revision ID: c194ea5daad5
Revises: 651659e1a779
Create Date: 2018-07-17 14:38:13.560540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c194ea5daad5'
down_revision = '651659e1a779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck', sa.Column('name', sa.String(length=250), nullable=False))
    op.drop_column('deck', 'deck')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck', sa.Column('deck', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('deck', 'name')
    # ### end Alembic commands ###
