"""empty message

Revision ID: c1bbd1bee8c2
Revises: 3e48f958bec1
Create Date: 2018-07-18 21:54:51.226061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bbd1bee8c2'
down_revision = '3e48f958bec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('indatabase', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'indatabase')
    # ### end Alembic commands ###
