"""empty message

Revision ID: c32b4ded4167
Revises: a39c78dee201
Create Date: 2018-07-18 15:39:07.255708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32b4ded4167'
down_revision = 'a39c78dee201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('type', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'type')
    # ### end Alembic commands ###
