"""empty message

Revision ID: daa7d0e7dedc
Revises: 3f67a1d92688
Create Date: 2018-07-24 00:48:05.582575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa7d0e7dedc'
down_revision = '3f67a1d92688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='player_pkey'),
    sa.UniqueConstraint('name', name='player_name_key')
    )
    # ### end Alembic commands ###
